# docker-compose.yaml
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql:host=db;dbname=devdb
      DATABASE_USER: devuser
      DATABASE_PASSWORD: devsecret
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName=raffle_prizes"
    working_dir: /var/www
    volumes:
      - ./src:/var/www

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  db:
    image: mariadb:10.5.8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_USER: devuser
      MYSQL_DATABASE: devdb
      MYSQL_PASSWORD: devsecret
      MYSQL_ROOT_PASSWORD: devsecret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: